name: PartyChat
version: ${project.version}
main: lol.hyper.partychat.PartyChat
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/partychat.88947/
description: A simple party chat plugin.
commands:
  party:
    description: The main party command.
  pc:
    description: Send private party messages.
    aliases: [p]
libraries:
  - org.json:json:20211205
  - commons-io:commons-io:2.11.0
  - lol.hyper:github-release-api:1.0.1