name: PartyChat
version: ${project.version}
main: lol.hyper.partychat.PartyChat
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/partychat.88947/
description: A simple party chat plugin.
folia-supported: true
commands:
  party:
    description: The main party command.
  pc:
    description: Send private party messages.
    aliases: [p]